In [16]:
import pandas as pd
import random as rand
from faker import Faker

In [12]:
data = {
    'StudentFName': [Faker().name() for i in range(30)],
    'StudentLName': [Faker().last_name() for i in range(30)],
    'age': [rand.randint(13, 15) for i in range(30)],
    'grades': [rand.randint(40, 100) for i in range(30)]
}

In [13]:
data

{'StudentFName': ['Steven Sherman',
  'Erica Scott',
  'Glenn Hughes',
  'Tina Gutierrez',
  'Lisa Hatfield',
  'Jennifer Rodriguez',
  'Henry Martinez',
  'Mark Clark',
  'Matthew Jacobs MD',
  'Connor Lewis',
  'Nicole Smith',
  'Jessica Lawrence',
  'Catherine Reed',
  'Kyle Johnson',
  'Michele Torres',
  'Deborah Wright',
  'Joseph Proctor',
  'Jeffery Martin',
  'Andrea Webster',
  'Kelly Stafford',
  'Edward Johnson',
  'Katherine Carter',
  'Maria Martinez',
  'Andrew Rosales',
  'Kevin Jackson',
  'Cynthia Johnson',
  'Susan Martin',
  'Julie Farley',
  'David Velasquez',
  'Amy Burke'],
 'StudentLName': ['Eaton',
  'Martinez',
  'Ward',
  'Hicks',
  'Simon',
  'Wilson',
  'Austin',
  'Carson',
  'Fletcher',
  'Ali',
  'Sanchez',
  'Diaz',
  'Medina',
  'Escobar',
  'Spears',
  'Foster',
  'Porter',
  'Sanchez',
  'Galloway',
  'Ferguson',
  'Bell',
  'Roberts',
  'Castro',
  'Perez',
  'Mack',
  'Davis',
  'Myers',
  'Wilson',
  'Adams',
  'Mathis'],
 'age': [14,
  15,
  15,
  13,
  15,
  15,
  14,
  15,
  15,
  13,
  15,
  15,
  13,
  14,
  13,
  14,
  15,
  15,
  13,
  15,
  13,
  14,
  14,
  14,
  14,
  14,
  13,
  15,
  13,
  14],
 'grades': [49,
  100,
  73,
  87,
  86,
  56,
  86,
  82,
  63,
  100,
  45,
  83,
  63,
  64,
  73,
  82,
  87,
  67,
  46,
  55,
  46,
  87,
  64,
  52,
  85,
  77,
  70,
  88,
  70,
  52]}

In [14]:
df = pd.DataFrame(data)

In [15]:
df

          StudentFName StudentLName  age  grades
0       Steven Sherman        Eaton   14      49
1          Erica Scott     Martinez   15     100
2         Glenn Hughes         Ward   15      73
3       Tina Gutierrez        Hicks   13      87
4        Lisa Hatfield        Simon   15      86
5   Jennifer Rodriguez       Wilson   15      56
6       Henry Martinez       Austin   14      86
7           Mark Clark       Carson   15      82
8    Matthew Jacobs MD     Fletcher   15      63
9         Connor Lewis          Ali   13     100
10        Nicole Smith      Sanchez   15      45
11    Jessica Lawrence         Diaz   15      83
12      Catherine Reed       Medina   13      63
13        Kyle Johnson      Escobar   14      64
14      Michele Torres       Spears   13      73
15      Deborah Wright       Foster   14      82
16      Joseph Proctor       Porter   15      87
17      Jeffery Martin      Sanchez   15      67
18      Andrea Webster     Galloway   13      46
19      Kelly Stafford     Ferguson   15      55
20      Edward Johnson         Bell   13      46
21    Katherine Carter      Roberts   14      87
22      Maria Martinez       Castro   14      64
23      Andrew Rosales        Perez   14      52
24       Kevin Jackson         Mack   14      85
25     Cynthia Johnson        Davis   14      77
26        Susan Martin        Myers   13      70
27        Julie Farley       Wilson   15      88
28     David Velasquez        Adams   13      70
29           Amy Burke       Mathis   14      52

In [22]:
data2 = {
    'EmployeeName': [Faker().name() for i in range(50)],
    'Address': [Faker().address() for i in range(50)],
    'age': [rand.randint(20,45) for i in range(50)],
    'phone': [Faker().phone_number() for i in range(50)],
    'email': [Faker().email() for i in range(50)]
}

In [23]:
df = pd.DataFrame(data2)
df

,EmployeeName,Address,age,phone,email
0,Benjamin Lopez,"905 Sheila Groves Suite 882\nMannland, PA 16302",28,(321)840-4769x2294,kwillis@example.net
1,Janice Mack,"705 Manning View\nNorth Thomas, RI 53822",30,001-955-918-6074,cstewart@example.net
2,Joseph Adams,USNS Smith\nFPO AP 73096,42,001-731-258-8122x06799,manningjoshua@example.org
3,Keith Vaughan,"4965 Miller Centers Suite 025\nSouth Tony, IN ...",43,(608)934-2870x4973,nicole30@example.com
4,Sharon Riddle,"1830 Robert Forks\nReyesberg, ND 13586",37,591.791.6270x404,heather96@example.org
5,David Smith,"7818 Stacey Loop\nSouth Eric, TN 36192",45,+1-586-815-5528,robertsphillip@example.com
6,Zachary Harris,"5063 Walker Shoals Apt. 415\nSouth Robertstad,...",34,+1-575-354-7372x07048,bjackson@example.org
7,Michael Hutchinson,"12868 Saunders Circle Suite 287\nWaltersfort, ...",30,899-422-1088,christopherstewart@example.com
8,Trevor Lee,"3768 Snyder Turnpike\nSmithmouth, MT 81852",38,310.983.1646x3147,crobbins@example.org
9,Matthew Garcia,"51247 Jones Lodge Apt. 659\nDavidsonfurt, UT 3...",29,516.652.1597,jensencynthia@example.net
10,Bruce Long,"0579 Carly Station Suite 983\nLake Juanbury, S...",29,601-687-2139x61881,ebonyschultz@example.net
11,Russell Krueger,"13763 Jimenez Shoals Apt. 602\nWaltersside, ME...",33,303-573-5424,beniteztimothy@example.com
12,Christine Mcbride,"607 Michael Walks\nLake Janetton, NM 07931",42,(884)779-3771,zschmidt@example.com
13,Carrie Price,"655 Baker Street\nArthurbury, AR 02744",36,(260)840-4440x225,williamclarke@example.com
14,Jay Chapman,"218 Jennifer Burgs Suite 424\nKellyland, PW 72031",34,526-306-6272x1150,pottssamantha@example.org
15,Christine Zamora,"2011 Cheryl Shores\nNew Wendy, VA 06446",30,7446168313,ssmith@example.org
16,Jody Tyler,"6319 Davidson Locks\nGarrettton, AR 34033",36,753-997-2406,sarah44@example.com
17,Julie Parker,"27591 Spencer Harbors\nRogermouth, WA 56074",43,481.362.4885,fchavez@example.org
18,Robert Bradford,"9287 Mitchell Overpass\nCoxchester, WV 98416",45,+1-306-702-3032x15289,kjones@example.com
19,Christopher Roman,"5005 Robert Plaza\nKathrynmouth, HI 61384",38,504.302.8693x63437,mary63@example.net
20,Tammy Chaney,48887 Matthew Pine Apt. 131\nSouth Thomashaven...,27,913.434.8743,walkermary@example.net
21,Jonathan Gray,"00712 Marcus Rapid\nBriannamouth, NH 52299",30,(450)877-1745,nicholasschneider@example.net
22,Dr. Anthony Willis DDS,"0250 Mckinney Via Apt. 311\nValenzuelaburgh, N...",31,6303076411,ricejennifer@example.com
23,Robert Butler,"PSC 3256, Box 1449\nAPO AA 96939",27,+1-308-418-4686x021,kevin06@example.org
24,Zachary Lara,"53681 Andrew Fork\nTuckerborough, IN 22675",27,(548)270-1774,gmeza@example.net
25,Jonathon Mitchell,"90354 Rivera Fall Apt. 449\nNorth Karenville, ...",25,(269)604-1285,taylortanya@example.org
26,Stephanie Davis,"917 Laura Isle Apt. 865\nEast Gregoryview, DE ...",41,+1-318-571-5463x987,michellegray@example.org
27,Sarah Thomas,"4630 Lauren Falls Suite 290\nLake Sierrastad, ...",31,633.570.3605x2383,wward@example.com
28,Randall Bailey,USS Petersen\nFPO AP 13542,38,829.945.9577x49438,larsondiane@example.com
29,Sandra Beltran,"0354 Mendez Glen Apt. 032\nEast Alyssaport, TX...",22,640.245.7916x78194,whitesara@example.com
30,Amber Brown,"0994 Haynes Center\nEast Keith, CA 64019",35,7413743651,daniel03@example.com
31,Rebecca Long,"12239 Melissa Port Apt. 398\nNew Thomas, DE 56322",36,909-686-9629x722,zdorsey@example.net
32,Christopher Monroe,"05178 Green Rue Apt. 848\nSouth Nicolehaven, K...",45,651-267-7010x1443,austingutierrez@example.org
33,Adam Morris,"630 Moss Ways Suite 709\nJeromeberg, IN 72548",29,288.316.7069x45100,donaldsonchristopher@example.org
34,Jesse Jackson,"058 David Rue\nEast Heatherbury, NE 84179",38,818-928-3633x121,hrobertson@example.com
35,Daniel Vance,Unit 9902 Box 9596\nDPO AA 95778,32,5748111177,fanderson@example.com
36,David Hall,"7087 Michael Lock Suite 122\nNew Jessica, NY 5...",44,201.342.1246,smurphy@example.org
37,Kara Dennis,USNS Mata\nFPO AA 61394,24,227-598-8901x5896,brian97@example.net
38,Ann Guzman,"5814 Rivera Route Apt. 870\nLinfurt, HI 48709",45,6848495669,warrenlauren@example.com
39,Melissa James,"198 Kimberly Lodge Apt. 685\nPatelmouth, WV 58246",34,(916)443-0859,chenheather@example.org
40,Crystal Perry,"491 Regina Lane\nSouth Robert, PA 45306",30,(687)679-7908x65342,taylor99@example.org
41,Cheryl Jones,5501 Frederick Ways Apt. 953\nWest Richardside...,42,+1-495-577-1150,sandra21@example.net
42,Jamie Juarez,"358 Ramos Tunnel Suite 826\nPort Melvin, WV 45158",20,001-566-604-8287x4891,cjones@example.org
43,Michael White,"7645 Bell Prairie Suite 489\nSouth Jeffrey, SC...",40,001-935-299-9178x219,christopherknox@example.com
44,Adam Clayton,"563 Anthony Knoll\nLake Alicialand, LA 38388",20,+1-669-695-0959x62604,vthompson@example.org
45,Cindy Hurst,"777 Middleton Squares\nChristopherstad, IA 55314",29,2073048202,mary23@example.org
46,Samuel Stephens,"976 Dawn Stravenue\nWest David, CA 67711",45,884-540-5292,anthony79@example.net
47,Anthony Garcia,"16597 Garcia Flat Apt. 861\nNorth Danielle, MA...",26,(808)469-3673x2364,stephensjoshua@example.net
48,Robert Orozco,"8685 Dorsey Locks Suite 067\nWest Amy, IL 74196",43,899-830-0440x9183,danielyork@example.net
49,Dawn Lyons MD,"709 Jason Shoal\nSarahborough, NJ 50199",35,001-910-383-2883x7536,sandracarson@example.net